// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvgqumjtildmncgzhhwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2Z3F1bWp0aWxkbW5jZ3poaHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0NDExMjQsImV4cCI6MjA5MDAxNzEyNH0.qjm1pQh3EETMJKp_l5SQzZqau5yINPWC1EX176dGuoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});